## Keras Basics (understanding with an example)

We'll start with some data on currency bank notes.

Some of these notes are legitimate and some forgeries.

The researchers created a dataset from these bank notes by taking images of the notes and then extracting various numerical features based off the wavelets of the images.

**Let's load that data and then try to a model on that data which can predict which is data of a legitimate note and which isn't**

In [1]:
# Import the tools
import numpy as np
from numpy import genfromtxt

In [4]:
data=genfromtxt('bank_note_data.txt',delimiter=',')

In [5]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In this data array last column will act as our labels for training data set

0 means forged note and 1 means legitimate note

In [8]:
len(data)  # length of this data

1372

In [10]:
# Let's seperate our labels from the data

labels=data[:,4]
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [11]:
# Let's seperate the remaining data from the labels

features=data[:,0:4]
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

Perfect!! now let's store them into X and y

In [13]:
X=features
y=labels

In [14]:
# Now seperate this data into training data set and testing that set we will keep the ratio of 70 and 30

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [15]:
len(X_train)

960

In [16]:
len(y_train)

960

In [17]:
# Now let's scale or standardized our data

from sklearn.preprocessing import MinMaxScaler

scaler_object=MinMaxScaler()

scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [19]:
# Now let's transform the training data

scaled_X_train=scaler_object.transform(X_train)

In [22]:
# Now let's transform the test data

scaled_X_test=scaler_object.transform(X_test)

In [25]:
# As you can see our training data set is normalized between the range of 0 and 1
scaled_X_train.min(),scaled_X_train.max()

(0.0, 1.0000000000000002)

### We are done with our data so let's build a model for our problem using Keras

In [28]:
from keras.models import Sequential
from keras.layers import Dense

In [36]:
model=Sequential()  # A Sequential model is appropriate for a plain stack of layers where each layer has exactly one input tensor and one output tensor.
model.add(Dense(4,input_dim=4,activation="relu"))  # We are using relu activation function for input layer neurons
model.add(Dense(8,activation="relu"))             # Hidden layer with 8 units and relu activation function
model.add(Dense(1,activation='sigmoid'))          # Output layer give one output and activation function is sigmoid 

# For compilation we are using cross entropy cost function , our optimizer is adam and metrics on which we will evaluate our function is accuracy
model.compile(loss="binary_crossentropy",optimizer="adam",metrics=["accuracy"])

model.fit(scaled_X_train,y_train,epochs=50,verbose=2)



Epoch 1/50
 - 0s - loss: 0.6679 - acc: 0.5552
Epoch 2/50
 - 0s - loss: 0.6523 - acc: 0.5552
Epoch 3/50
 - 0s - loss: 0.6380 - acc: 0.5552
Epoch 4/50
 - 0s - loss: 0.6207 - acc: 0.5865
Epoch 5/50
 - 0s - loss: 0.6030 - acc: 0.6167
Epoch 6/50
 - 0s - loss: 0.5860 - acc: 0.6510
Epoch 7/50
 - 0s - loss: 0.5685 - acc: 0.7135
Epoch 8/50
 - 0s - loss: 0.5511 - acc: 0.7552
Epoch 9/50
 - 0s - loss: 0.5333 - acc: 0.7635
Epoch 10/50
 - 0s - loss: 0.5148 - acc: 0.7906
Epoch 11/50
 - 0s - loss: 0.4956 - acc: 0.8031
Epoch 12/50
 - 0s - loss: 0.4754 - acc: 0.8188
Epoch 13/50
 - 0s - loss: 0.4511 - acc: 0.8344
Epoch 14/50
 - 0s - loss: 0.4178 - acc: 0.8833
Epoch 15/50
 - 0s - loss: 0.3916 - acc: 0.8979
Epoch 16/50
 - 0s - loss: 0.3678 - acc: 0.9104
Epoch 17/50
 - 0s - loss: 0.3454 - acc: 0.9146
Epoch 18/50
 - 0s - loss: 0.3248 - acc: 0.9281
Epoch 19/50
 - 0s - loss: 0.3058 - acc: 0.9312
Epoch 20/50
 - 0s - loss: 0.2876 - acc: 0.9333
Epoch 21/50
 - 0s - loss: 0.2722 - acc: 0.9396
Epoch 22/50
 - 0s - lo

In [37]:
predictions=model.predict_classes(scaled_X_test)

# Model metrics
from sklearn.metrics import confusion_matrix,classification_report

confusion_matrix(y_test,predictions)

array([[226,   3],
       [  8, 175]], dtype=int64)

In [38]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.97      0.99      0.98       229
        1.0       0.98      0.96      0.97       183

avg / total       0.97      0.97      0.97       412



In [39]:
# Save and load model
model.save("my_model.h5")

In [40]:
from keras.models import load_model
new_model=load_model('my_model.h5')